[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22.15.0"

# =============================================================================
# Environment variables for different deploy contexts
#
# IMPORTANT:
# Replace the placeholder URLs below with your actual API URLs.
# - 'production' is for your main live site.
# - 'deploy-preview' is for pull/merge request previews.
# =============================================================================

[context.production.environment]
  # TODO: Replace with your production API URL
  NEXT_PUBLIC_API_URL = "https://fin-ai-backend.fin-ai-api.my.id/api/v1"

[context.deploy-preview.environment]
  # TODO: Replace with your staging or preview API URL
  NEXT_PUBLIC_API_URL = "https://fin-ai-backend.fin-ai-api.my.id/api/v1"