import { categories } from './categories';

function getCategoryData(categoryName: string) {
  return categories.find((cat) => cat.name === categoryName) || null;
}

export const dummyResponseHistory = {
  success: 'success retrieved history',
  code: 200,
  data: [
    {
      id: 1,
      type: 'Pengeluaran',
      desc: 'Makan Siang',
      category: 'Food',
      amount: 50000,
      date: '2025-06-19',
    },
    {
      id: 2,
      type: 'Pemasukan',
      desc: 'Gaji',
      category: 'Salary',
      amount: 3000000,
      date: '2025-06-18',
    },
    {
      id: 3,
      type: 'Pengeluaran',
      desc: 'Transport',
      category: 'Transportation',
      amount: 20000,
      date: '2025-06-18',
    },
    {
      id: 4,
      type: 'Pengeluaran',
      desc: 'Ngopi',
      category: 'Food',
      amount: 25000,
      date: '2025-06-17',
    },
    {
      id: 5,
      type: 'Pemasukan',
      desc: 'Bonus Kinerja',
      category: 'Salary',
      amount: 500000,
      date: '2025-06-16',
    },
    {
      id: 6,
      type: 'Pengeluaran',
      desc: 'Belanja Bulanan',
      category: 'Food',
      amount: 750000,
      date: '2025-06-15',
    },
    {
      id: 7,
      type: 'Pengeluaran',
      desc: 'Bayar Listrik',
      category: 'Utilities',
      amount: 200000,
      date: '2025-06-14',
    },
    {
      id: 8,
      type: 'Pengeluaran',
      desc: 'Bensin Motor',
      category: 'Transportation',
      amount: 35000,
      date: '2025-06-13',
    },
    {
      id: 9,
      type: 'Pemasukan',
      desc: 'Freelance Project',
      category: 'Salary',
      amount: 1200000,
      date: '2025-06-12',
    },
    {
      id: 10,
      type: 'Pengeluaran',
      desc: 'Makan Malam',
      category: 'Food',
      amount: 85000,
      date: '2025-06-11',
    },
  ],
  pagination: {
    total: 20,
    currentPage: 1,
    totalPages: 2,
  },
};

export const dummyResponseHistory2 = {
  success: 'success retrieved history',
  code: 200,
  data: [
    {
      id: 11,
      type: 'Pengeluaran',
      desc: 'Beli Buku',
      category: 'Education',
      amount: 150000,
      date: '2025-06-10',
    },
    {
      id: 12,
      type: 'Pemasukan',
      desc: 'Jual Barang Bekas',
      category: 'Education',
      amount: 200000,
      date: '2025-06-09',
    },
    {
      id: 13,
      type: 'Pengeluaran',
      desc: 'Makan Pagi',
      category: 'Food',
      amount: 30000,
      date: '2025-06-08',
    },
    {
      id: 14,
      type: 'Pengeluaran',
      desc: 'Biaya Internet',
      category: 'Utilities',
      amount: 100000,
      date: '2025-06-07',
    },
    {
      id: 15,
      type: 'Pemasukan',
      desc: 'Hadiah Ulang Tahun',
      category: 'Gift',
      amount: 500000,
      date: '2025-06-06',
    },
    {
      id: 16,
      type: 'Pengeluaran',
      desc: 'Makan Malam di Restoran',
      category: 'Food',
      amount: 120000,
      date: '2025-06-05',
    },
    {
      id: 17,
      type: 'Pengeluaran',
      desc: 'Belanja Online',
      category: 'Utilities',
      amount: 300000,
      date: '2025-06-04',
    },
    {
      id: 18,
      type: 'Pemasukan',
      desc: 'Bonus Proyek Selesai',
      category: 'Salary',
      amount: 800000,
      date: '2025-06-03',
    },
    {
      id: 19,
      type: 'Pengeluaran',
      desc: 'Beli Makanan Hewan Peliharaan',
      category: 'Food',
      amount: 60000,
      date: '2025-06-02',
    },
    {
      id: 20,
      type: 'Pemasukan',
      desc: 'Pendapatan Sampingan Freelance',
      category: 'Salary',
      amount: 400000,
      date: '2025-06-01',
    },
  ],
  pagination: {
    total: 20,
    currentPage: 2,
    totalPages: 2,
  },
};
